name: Deploy Static Images to GitHub Pages

on:
  push:
    branches:
      - main # 或者你选择的分支名称
    paths:
      - 'img/**' # 只有 img 文件夹下的文件更改才会触发工作流
      - '.github/workflows/deploy.yml' # 如果更改了工作流文件本身也会触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build static site
      run: |
        # 运行你的 Node.js 脚本来生成静态内容
        node server.js
        # 如果你需要其他构建步骤，可以在这里添加

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # 默认根目录，假设生成的静态内容是在根目录下
        force_orphan: true